from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]

def uuid(c):
    return f"typeof({c})='text' AND length({c})=36 AND substr({c},9,1)='-' AND substr({c},14,1)='-' AND substr({c},19,1)='-' AND substr({c},24,1)='-' AND length(replace({c},'-',''))=32 AND replace({c},'-','') NOT GLOB '*[^0-9a-f]*'"

def day(c):
    y=f'CAST(substr({c},1,4) AS INTEGER)'; m=f'CAST(substr({c},6,2) AS INTEGER)'; d=f'CAST(substr({c},9,2) AS INTEGER)'
    return f"typeof({c})='text' AND length({c})=10 AND {c} GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' AND {y} BETWEEN 1 AND 9999 AND {m} BETWEEN 1 AND 12 AND {d} BETWEEN 1 AND CASE WHEN {m}=2 THEN 28+CASE WHEN ({y}%4=0 AND ({y}%100<>0 OR {y}%400=0)) THEN 1 ELSE 0 END WHEN {m} IN (4,6,9,11) THEN 30 ELSE 31 END"

def instant(c):
    return f"typeof({c})='text' AND length({c})=24 AND ({day(f'substr({c},1,10)')}) AND substr({c},11) GLOB 'T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z' AND CAST(substr({c},12,2) AS INTEGER) BETWEEN 0 AND 23 AND CAST(substr({c},15,2) AS INTEGER) BETWEEN 0 AND 59 AND CAST(substr({c},18,2) AS INTEGER) BETWEEN 0 AND 59"

def text(c): return f"{c} TEXT NOT NULL CHECK(typeof({c})='text' AND length(trim({c}))>0)"
def uid(c): return f'{c} TEXT NOT NULL CHECK({uuid(c)})'
def ts(c, optional=False): return f"{c} TEXT {'CHECK('+c+' IS NULL OR '+instant(c)+')' if optional else 'NOT NULL CHECK('+instant(c)+')'}"
def integer(c, rule, default=''): return f"{c} INTEGER NOT NULL {default} CHECK(typeof({c})='integer' AND {rule})"
def scope(): return f'{uid("owner_user_id")},\n  {uid("clinic_id")}'
def context_fk(): return 'FOREIGN KEY(owner_user_id,clinic_id) REFERENCES local_contexts(owner_user_id,clinic_id) ON DELETE RESTRICT'
def sha(c): return f"{c} TEXT NOT NULL CHECK(typeof({c})='text' AND length({c})=64 AND {c} NOT GLOB '*[^0-9a-f]*')"
def decimal(c, optional=False):
    rule=f"typeof({c})='text' AND length({c}) BETWEEN 1 AND 19 AND {c} NOT GLOB '*[^0-9]*' AND ({c}='0' OR substr({c},1,1)<>'0') AND (length({c})<19 OR {c}<='9223372036854775807')"
    return f"{c} TEXT {'CHECK('+c+' IS NULL OR ('+rule+'))' if optional else 'NOT NULL CHECK('+rule+')'}"

sql=f'''-- Generated by database/sqlite/build_schema.py. SQLite schema v2.
-- Fresh installation only; existing databases must use migrate.ts/migrate.py.
-- No credentials here. Confirmed cache is replaceable; pending uploads are not.
PRAGMA foreign_keys=ON;
CREATE TABLE local_contexts (
  {scope()},
  role TEXT NOT NULL CHECK(role IN ('CLINIC_ADMIN','CLINICIAN','PATIENT')),
  {decimal('permission_revision')} CHECK(permission_revision<>'0'),
  access_state TEXT NOT NULL CHECK(access_state IN ('READ_WRITE','READ_ONLY','REVOKED')),
  {ts('updated_at')},
  PRIMARY KEY(owner_user_id,clinic_id)
);
CREATE TABLE local_patients (
  {scope()}, {uid('id')}, {uid('user_id')},
  {text('first_name')}, {text('last_name')},
  date_of_birth TEXT NOT NULL CHECK({day('date_of_birth')}),
  email TEXT CHECK(email IS NULL OR typeof(email)='text'), phone TEXT CHECK(phone IS NULL OR typeof(phone)='text'), medical_record_number TEXT CHECK(medical_record_number IS NULL OR (typeof(medical_record_number)='text' AND length(trim(medical_record_number))>0)),
  {integer('is_active','is_active IN (0,1)')},
  {ts('deleted_at',True)}, {ts('updated_at')},
  PRIMARY KEY(owner_user_id,clinic_id,id),
  UNIQUE(owner_user_id,clinic_id,user_id), {context_fk()}
);
CREATE TABLE local_exams (
  {scope()}, {uid('id')}, {uid('patient_id')},
  {text('exam_type_code')}, {text('exam_type_name')}, {text('title')},
  exam_date TEXT NOT NULL CHECK({day('exam_date')}),
  professional_name TEXT CHECK(professional_name IS NULL OR typeof(professional_name)='text'), notes TEXT CHECK(notes IS NULL OR typeof(notes)='text'),
  current_version INTEGER CHECK(current_version IS NULL OR (typeof(current_version)='integer' AND current_version>=1)),
  latest_server_version INTEGER NOT NULL CHECK(typeof(latest_server_version)='integer' AND latest_server_version>=1),
  {ts('updated_at')},
  PRIMARY KEY(owner_user_id,clinic_id,id),
  FOREIGN KEY(owner_user_id,clinic_id,patient_id) REFERENCES local_patients(owner_user_id,clinic_id,id) ON DELETE CASCADE
);
CREATE INDEX idx_local_exams_timeline ON local_exams(owner_user_id,clinic_id,patient_id,exam_date,id);
CREATE TABLE local_exam_versions (
  {scope()}, {uid('id')}, {uid('exam_id')},
  {integer('version_number','version_number>=1')},
  {text('original_filename')},
  mime_type TEXT NOT NULL CHECK(mime_type IN ('application/pdf','image/jpeg','image/png')),
  {integer('size_bytes','size_bytes BETWEEN 1 AND 10000000')}, {sha('sha256')},
  local_file_uri TEXT CHECK(local_file_uri IS NULL OR (typeof(local_file_uri)='text' AND local_file_uri LIKE 'file:///%')),
  {ts('verified_at',True)}, {ts('created_at')},
  CHECK((local_file_uri IS NULL)=(verified_at IS NULL)),
  PRIMARY KEY(owner_user_id,clinic_id,id),
  UNIQUE(owner_user_id,clinic_id,exam_id,version_number),
  FOREIGN KEY(owner_user_id,clinic_id,exam_id) REFERENCES local_exams(owner_user_id,clinic_id,id) ON DELETE CASCADE
);
CREATE TABLE sync_queue (
  {scope()}, {uid('id')}, {uid('patient_id')}, {uid('exam_id')}, {uid('version_id')},
  operation TEXT NOT NULL CHECK(operation IN ('CREATE_EXAM_WITH_VERSION','UPLOAD_VERSION')),
  payload TEXT NOT NULL CHECK(CASE WHEN json_valid(payload) THEN coalesce(
    json_type(payload)='object' AND json_type(payload,'$.schemaVersion')='integer' AND json_extract(payload,'$.schemaVersion')=1
    AND json_extract(payload,'$.patientId')=patient_id AND json_extract(payload,'$.examId')=exam_id
    AND json_extract(payload,'$.versionId')=version_id
    AND (operation='UPLOAD_VERSION' OR (json_type(payload,'$.title')='text' AND length(trim(json_extract(payload,'$.title')))>0
      AND ({day("json_extract(payload,'$.examDate')")}) AND ({uuid("json_extract(payload,'$.examTypeId')")}))),0) ELSE 0 END),
  {text('file_uri')} CHECK(file_uri LIKE 'file:///%'),
  {sha('sha256')}, {sha('request_hash')},
  mime_type TEXT NOT NULL CHECK(mime_type IN ('application/pdf','image/jpeg','image/png')),
  {integer('size_bytes','size_bytes BETWEEN 1 AND 10000000')}, {text('original_filename')},
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','PROCESSING','FAILED','COMPLETED')),
  {integer('retry_count','retry_count BETWEEN 0 AND 8','DEFAULT 0')},
  {integer('is_retryable','is_retryable IN (0,1)','DEFAULT 1')},
  {text('pause_reason').replace('NOT NULL','').replace('CHECK(typeof(pause_reason)', 'CHECK(pause_reason IS NULL OR typeof(pause_reason)')},
  {ts('next_attempt_at',True)}, {ts('processing_until',True)}, last_error TEXT,
  {ts('created_at')}, {ts('updated_at')},
  CHECK((status='PROCESSING')=(processing_until IS NOT NULL)),
  PRIMARY KEY(owner_user_id,clinic_id,id),
  UNIQUE(owner_user_id,clinic_id,version_id), {context_fk()}
);
CREATE INDEX idx_sync_queue_ready ON sync_queue(owner_user_id,clinic_id,status,next_attempt_at);
CREATE TABLE sync_metadata (
  {scope()}, stream TEXT NOT NULL CHECK(stream='clinical'),
  cursor TEXT CHECK(cursor IS NULL OR (typeof(cursor)='text' AND length(cursor)>0)),
  {decimal('revision')}, {ts('updated_at')},
  PRIMARY KEY(owner_user_id,clinic_id,stream), {context_fk()}
);
-- Survives removal of cache rows; the client deletes physical files and acknowledges.
CREATE TABLE local_file_cleanup (
  {scope()}, {text('file_uri')},
  PRIMARY KEY(owner_user_id,clinic_id,file_uri)
);
-- Raw legacy queue is retained without guessing its account or tenant.
CREATE TABLE legacy_queue_quarantine (
  legacy_rowid INTEGER NOT NULL PRIMARY KEY,
  raw_record TEXT NOT NULL CHECK(json_valid(raw_record)),
  file_uri TEXT,
  reason TEXT NOT NULL DEFAULT 'UNVERIFIED_OWNER_AND_CLINIC'
);
'''
condition="owner_user_id=NEW.owner_user_id AND clinic_id=NEW.clinic_id AND exam_id=NEW.exam_id"
recalc=f"UPDATE local_exams SET current_version=(SELECT max(version_number) FROM local_exam_versions WHERE {condition} AND verified_at IS NOT NULL) WHERE owner_user_id=NEW.owner_user_id AND clinic_id=NEW.clinic_id AND id=NEW.exam_id;"
sql+=f'''
CREATE TRIGGER version_download_insert AFTER INSERT ON local_exam_versions BEGIN {recalc} END;
CREATE TRIGGER version_download_update AFTER UPDATE OF local_file_uri,verified_at ON local_exam_versions BEGIN
  INSERT OR IGNORE INTO local_file_cleanup SELECT OLD.owner_user_id,OLD.clinic_id,OLD.local_file_uri WHERE OLD.local_file_uri IS NOT NULL AND OLD.local_file_uri IS NOT NEW.local_file_uri;
  {recalc}
END;
CREATE TRIGGER version_download_delete AFTER DELETE ON local_exam_versions BEGIN
  INSERT OR IGNORE INTO local_file_cleanup SELECT OLD.owner_user_id,OLD.clinic_id,OLD.local_file_uri WHERE OLD.local_file_uri IS NOT NULL;
  {recalc.replace('NEW.','OLD.')}
END;
CREATE TRIGGER current_version_derived BEFORE UPDATE OF current_version ON local_exams
WHEN NEW.current_version IS NOT (SELECT max(version_number) FROM local_exam_versions WHERE owner_user_id=NEW.owner_user_id AND clinic_id=NEW.clinic_id AND exam_id=NEW.id AND verified_at IS NOT NULL)
BEGIN SELECT RAISE(ABORT,'current_version is derived from verified downloads'); END;
CREATE TRIGGER no_initial_download BEFORE INSERT ON local_exams WHEN NEW.current_version IS NOT NULL
BEGIN SELECT RAISE(ABORT,'An initial cached exam has no verified download'); END;
CREATE TRIGGER version_metadata_immutable BEFORE UPDATE ON local_exam_versions
WHEN NEW.owner_user_id IS NOT OLD.owner_user_id OR NEW.clinic_id IS NOT OLD.clinic_id OR NEW.id IS NOT OLD.id
 OR NEW.exam_id IS NOT OLD.exam_id OR NEW.version_number IS NOT OLD.version_number OR NEW.sha256 IS NOT OLD.sha256
 OR NEW.size_bytes IS NOT OLD.size_bytes OR NEW.mime_type IS NOT OLD.mime_type OR NEW.original_filename IS NOT OLD.original_filename OR NEW.created_at IS NOT OLD.created_at
BEGIN SELECT RAISE(ABORT,'Confirmed version metadata is immutable'); END;
CREATE TRIGGER queue_identity_immutable BEFORE UPDATE ON sync_queue
WHEN NEW.owner_user_id IS NOT OLD.owner_user_id OR NEW.clinic_id IS NOT OLD.clinic_id OR NEW.id IS NOT OLD.id
 OR NEW.operation IS NOT OLD.operation OR NEW.payload IS NOT OLD.payload OR NEW.exam_id IS NOT OLD.exam_id
 OR NEW.patient_id IS NOT OLD.patient_id OR NEW.version_id IS NOT OLD.version_id OR NEW.request_hash IS NOT OLD.request_hash
 OR NEW.file_uri IS NOT OLD.file_uri OR NEW.sha256 IS NOT OLD.sha256 OR NEW.size_bytes IS NOT OLD.size_bytes
 OR NEW.mime_type IS NOT OLD.mime_type OR NEW.original_filename IS NOT OLD.original_filename
BEGIN SELECT RAISE(ABORT,'Retry must preserve upload identity and content'); END;
CREATE TRIGGER queue_claim_authorized BEFORE UPDATE OF status ON sync_queue
WHEN NEW.status='PROCESSING' AND (NEW.pause_reason IS NOT NULL OR NEW.retry_count>8 OR NEW.is_retryable<>1
 OR NOT EXISTS(SELECT 1 FROM local_contexts WHERE owner_user_id=NEW.owner_user_id AND clinic_id=NEW.clinic_id AND access_state='READ_WRITE'))
BEGIN SELECT RAISE(ABORT,'Queue cannot process without write access'); END;
CREATE TRIGGER protect_pending_delete BEFORE DELETE ON sync_queue WHEN OLD.status<>'COMPLETED'
BEGIN SELECT RAISE(ABORT,'Pending uploads require explicit user resolution, not deletion'); END;
CREATE TRIGGER queue_completed_cleanup AFTER UPDATE OF status ON sync_queue WHEN NEW.status='COMPLETED' AND OLD.status<>'COMPLETED'
BEGIN INSERT OR IGNORE INTO local_file_cleanup VALUES(NEW.owner_user_id,NEW.clinic_id,NEW.file_uri); END;
CREATE TRIGGER patient_cache_scope BEFORE INSERT ON local_patients
WHEN EXISTS(SELECT 1 FROM local_contexts WHERE owner_user_id=NEW.owner_user_id AND clinic_id=NEW.clinic_id AND role='PATIENT') AND NEW.user_id<>NEW.owner_user_id
BEGIN SELECT RAISE(ABORT,'A patient context caches only its own patient'); END;
CREATE TRIGGER patient_cache_scope_update BEFORE UPDATE OF user_id ON local_patients
WHEN EXISTS(SELECT 1 FROM local_contexts WHERE owner_user_id=NEW.owner_user_id AND clinic_id=NEW.clinic_id AND role='PATIENT') AND NEW.user_id<>NEW.owner_user_id
BEGIN SELECT RAISE(ABORT,'A patient context caches only its own patient'); END;
CREATE TRIGGER queue_initial_state BEFORE INSERT ON sync_queue WHEN NEW.status<>'PENDING' OR NEW.retry_count<>0
BEGIN SELECT RAISE(ABORT,'New uploads must start pending with no attempts'); END;
CREATE TRIGGER version_within_server_range BEFORE INSERT ON local_exam_versions
WHEN NEW.version_number>(SELECT latest_server_version FROM local_exams WHERE owner_user_id=NEW.owner_user_id AND clinic_id=NEW.clinic_id AND id=NEW.exam_id)
BEGIN SELECT RAISE(ABORT,'Version exceeds confirmed server version'); END;
CREATE TRIGGER server_version_monotonic BEFORE UPDATE OF latest_server_version ON local_exams
WHEN NEW.latest_server_version<OLD.latest_server_version
BEGIN SELECT RAISE(ABORT,'Confirmed version number cannot go backwards'); END;
CREATE TRIGGER cursor_monotonic BEFORE UPDATE OF revision ON sync_metadata
WHEN length(NEW.revision)<length(OLD.revision) OR (length(NEW.revision)=length(OLD.revision) AND NEW.revision<OLD.revision)
BEGIN SELECT RAISE(ABORT,'Sync revision cannot go backwards'); END;
PRAGMA user_version=2;
'''
for table in ['local_contexts','local_patients','local_exams','local_exam_versions','sync_queue','sync_metadata']:
    cols=['owner_user_id','clinic_id'] + (['id'] if table in ['local_patients','local_exams','local_exam_versions','sync_queue'] else [])
    condition=' OR '.join(f'NEW.{c} IS NOT OLD.{c}' for c in cols)
    sql+=f'\nCREATE TRIGGER scope_{table} BEFORE UPDATE ON {table} WHEN {condition} BEGIN SELECT RAISE(ABORT,\'Local scope is immutable\'); END;\n'
(ROOT/'database/sqlite_mobile_schema.sql').write_text(sql,encoding='utf-8')
if __name__=='__main__': print('Generated SQLite v2 schema')
