import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
const api=resolve(__dirname,'..');
const readSql=(path:string)=>readFileSync(path,'utf8').replace(/\r\n/g,'\n');
const migration=readSql(resolve(api,'prisma/migrations/20261001030827_init/migration.sql'));
const invariants=readSql(resolve(api,'../../database/postgresql/invariants.sql'));
const repair=readSql(resolve(api,'prisma/migrations/20261005120000_fix_protect_audit/migration.sql'));
const auditFunction=/CREATE (?:OR REPLACE )?FUNCTION protect_audit\(\)[\s\S]*?END \$\$;/;
const repairedAudit=repair.match(auditFunction)?.[0].replace('CREATE OR REPLACE FUNCTION','CREATE FUNCTION');
assert.ok(repairedAudit,'Audit repair migration must replace protect_audit');
const effectiveMigration=migration.replace(auditFunction,()=>repairedAudit!);
assert.ok(effectiveMigration.endsWith(invariants),'Custom SQL migrations are out of sync');
console.log('Custom PostgreSQL SQL is synchronized with the initial and repair migrations.');
